<!doctypehtml>
<htmlclass="no-js"lang="en">
<head>
<metacharset="utf-8"/>
<metaname="viewport"content="width=device-width,initial-scale=1.0"/>
<title>Template</title>
{{HTML::style('bower_components/foundation/css/foundation.css')}}
</head>
<body>
<divclass="row">
<divclass="columnslarge-12">
@yield('content')
</div>
</div>
{{HTML::script('bower_components/jquery/dist/jquery.js')}}
{{HTML::script('bower_components/foundation/js/foundation.min.js')}}
<script>
$(document).foundation();
</script>
</body>
</html>
